### ISSUE TITLE
Version 0.1.0

### ISSUE THREAD

**Issue by momega** [webjars/angular-google-chart#1]
Please,
 prepare latest upstream version 0.1.0
Thanks.

**Comment by momega** [comment]
Sorry,
but prepared webjar is not correct. There are 2 issues:
- it is not used official repository webjar
- the upstream version in pom.xml is wrong (still 0.0.8)

I have fixed it. See my forked repo:
https://github.com/momega/angular-google-chart

My pom.xml contains version 0.1.0.1-SNAPSHOT to be different than previous 0.1.0.

**Comment by jamesward** [comment]
Can you send a Pull Request with the necessary changes?
